"""Regression checks against manuscript values and unchanged annotations."""
import tempfile
import unittest
import json
from pathlib import Path

import numpy as np
import pandas as pd
import pyarrow.parquet as pq
from jsonschema import Draft202012Validator

from src.analysis.human_validate import _icc_2k, _design_score, run
from scripts.prepare_human_eval_release import export

ROOT = Path(__file__).resolve().parents[1]


class HumanValidationTests(unittest.TestCase):
    def test_paper_matrix_rows(self):
        # Columns: ICC, CI, Pearson r, MAD. Independently transcribed from
        # the manuscript, not generated by the implementation under test.
        expected = [
            (.916, "[0.86, 0.95]", .871, .513),
            (.980, "[0.94, 1.00]", .990, .350),
            (.983, "[0.95, 1.00]", .990, .350),
            (.973, "[0.92, 1.00]", .969, .267),
            (.951, "[0.86, 0.99]", .973, .250),
            (.964, "[0.90, 0.99]", .988, .250),
            (.908, "[0.74, 0.98]", .913, .350),
            (.931, "[0.81, 0.99]", .937, .383),
            (.972, "[0.92, 1.00]", .842, .500),
            (.945, "[0.85, 0.99]", .753, .300),
            (.895, "[0.71, 0.98]", .778, .267),
            (.962, "[0.95, 0.97]", .943, .327),
        ]
        with tempfile.TemporaryDirectory() as tmp:
            run(ROOT / "data", ROOT / "scoring_matrices", Path(tmp))
            actual = pd.read_csv(Path(tmp) / "tab_c_validation.tsv", sep="\t")
        self.assertEqual(len(actual), len(expected))
        for row, (icc, ci, r, mad) in zip(actual.itertuples(), expected):
            with self.subTest(row=row.row):
                self.assertAlmostEqual(row.icc_2k, icc)
                self.assertEqual(row.icc_ci, ci)
                self.assertAlmostEqual(row.pearson_r, r)
                self.assertAlmostEqual(row.mad, mad)

    def test_icc_degenerate_and_invalid_inputs(self):
        self.assertEqual(_icc_2k([[1, 1], [2, 2], [4, 4]]), (1., 1., 1.))
        self.assertTrue(all(np.isnan(x) for x in _icc_2k([[2, 2], [2, 2]])))
        for scores in ([[1, 2]], [[1], [2]], [[1, np.nan], [2, 3]]):
            with self.assertRaises(ValueError):
                _icc_2k(scores)

    def test_missing_design_cell_fails_instead_of_silent_exclusion(self):
        with self.assertRaises(ValueError):
            _design_score(ROOT / "scoring_matrices/ipa_matrix.tsv", "QI99", "SP1")

    def test_release_preserves_labels_scores_and_statistics(self):
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            manifest = export(ROOT / "data", root / "clean")
            validator = Draft202012Validator(json.loads((root / "clean/label_human_eval.schema.json").read_text()))
            self.assertEqual(len(manifest), 7)
            for item in manifest:
                before = pq.read_table(ROOT / "data" / item["file"])
                after = pq.read_table(root / "clean" / item["file"])
                self.assertNotIn("gpt4o_mini_reasoning", after.column_names)
                if "annotator_scores" in before.column_names:
                    for col in before.column_names:
                        if col not in ("mean", "median", "n"):
                            self.assertEqual(before[col].to_pylist(), after[col].to_pylist())
                    scores = before["annotator_scores"].to_pylist()
                    self.assertEqual(after["median"].to_pylist(), [float(np.median(s)) for s in scores])
                else:
                    retained = (before.drop(["gpt4o_mini_reasoning"])
                                if "gpt4o_mini_reasoning" in before.column_names else before)
                    self.assertTrue(retained.equals(after, check_metadata=False))
                    for row in after.to_pylist():
                        validator.validate(row)
            run(ROOT / "data", ROOT / "scoring_matrices", root / "before")
            run(root / "clean", ROOT / "scoring_matrices", root / "after")
            for name in ("tab_c_judge_kappa.tsv", "tab_c_validation.tsv"):
                self.assertEqual((root / "before" / name).read_bytes(), (root / "after" / name).read_bytes())


if __name__ == "__main__":
    unittest.main()
